### PR TITLE
Add CODEOWNERS file

### PR DESCRIPTION
**Pull request by artemdinaburg**
This is an automated pull request. It adds a CODEOWNERS file to the repository

### CODE REVIEW

**Review by postmodern — CHANGES_REQUESTED** [review]
I don't feel comfortable being the only `CODEOWNERS` responsible for reviewing PRs, seeing as how the [copyright](https://github.com/trailofbits/dkim-query/blob/f163ff1e2501709be04655bfb354e00cfe35072d/LICENSE.txt#L3) clearly states that this library is owned by Trail of Bits and I am not an active employee of Trail of Bits. Maybe an active employee should be tasked with reviewing PRs?

**Comment by woodruffw** [comment]
Yeah, I don't think it's right to have you be the sole codeowner. I don't have a lot of time to maintain these, but I can add myself to the `CODEOWNERS` so that at least someone at ToB also sees anything here.

**Comment by woodruffw** [comment]
Added myself. @postmodern I've left you in as a codeowner as well, but if you prefer to not be nagged on these I can take you out of the list 🙂

**Comment by woodruffw** [comment]
(Merging for now; I'll remove you in a follow-up in you'd like.)

**Pull request merged**
